name: booktrade
description: Selling and Trading between students
author: Badjessa B. Bahoumda
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: "^0.1.2"
  firebase_core: "0.2.5+1"
  firebase_auth: "0.6.2+1"
  firebase_storage: "^1.0.4"
  firebase_messaging: "^2.0.2"
  cloud_firestore: "^0.8.2+1"
  firebase_admob: "0.5.6"
  google_sign_in : "^3.2.2"
  flutter_search_bar: "^2.0.4"
  camera: "^0.2.1"
  path_provider: "^0.4.1"
  flutter_launcher_icons: "^0.6.1"
  modal_progress_hud: "^0.1.1"
  image_picker: "^0.4.10"
  validators: "^1.0.0"
  url_launcher: "^3.0.3"
  package_info: "^0.3.2"
  intro_views_flutter: "^2.3.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/img/logo.png"
  android: false
  ios: false
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf

  assets:
    - assets/img/logo.png
    - assets/img/icon launcher.png
    - assets/img/addBook.png
    - assets/img/buying.png
    - assets/img/menu.png
    - assets/img/search.png
    - assets/img/selling.png
    - assets/img/addBook2.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
